version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: assafdb
      MYSQL_USER: assafuser
      MYSQL_PASSWORD: assafpass

    volumes:
      - db_data:/var/lib/mysql
      - ./mysql.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: assaf
      DB_PASS: secret
      DB_NAME: assaf_media
      BREVO_API_KEY: ${BREVO_API_KEY}
      DEBUG: ${DEBUG:-0}
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "8080:80"

  frontend:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3001:80"
    depends_on:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
